### ISSUE TITLE
python run_AB.py

### ISSUE THREAD

**Issue by iancharest** [lajnd/pyExperiment#1]
File "run_AB.py", line 19
    path = os.path.join(STIM_FOLDER, f'image_{im:02d}.jpg')
SyntaxError: invalid syntax

**Comment by lajnd** [comment]
Are you on python 3.6+? https://realpython.com/python-f-strings/

**Comment by iancharest** [comment]
ok, now I got py3.6 but I now get this:
Traceback (most recent call last):
  File "run_AB.py", line 1, in <module>
    from psychopy.visual import ImageStim #import some libraries from PsychoPy
ModuleNotFoundError: No module named 'psychopy'

**Comment by iancharest** [comment]
i did install psychopy

**Comment by lajnd** [comment]
install psychopy! pip install psychopy

**Comment by lajnd** [comment]
Can you import it in an interactive shell?

**Comment by iancharest** [comment]
installing it with pip now

**Comment by lajnd** [comment]
Maybe you have the stand alone installation

**Comment by iancharest** [comment]
yes, looks like that

**Comment by iancharest** [comment]
pip install psychopy

Command "/home/adf/charesti/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5Qg9GZ/wxPython/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-RIP51Y-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-5Qg9GZ/wxPython/

**Comment by lajnd** [comment]
sudo it maybe?

**Comment by lajnd** [comment]
sudo pip install psychopy==1.90.1

**Comment by iancharest** [comment]
ok got it to work.

conda create --name py36 python=3.6

source activate py36

pip install -U     -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04     wxPython

pip install --upgrade pip

pip install psychopy
